repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        exclude: ^dist/

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    exclude: ^(.git|__pycache__|docs/source/conf.py|old|build|dist|tests|jina/resources/|docarray/proto/pb/docarray_pb2.py|docarray/proto/pb/docarray_pb2_grpc.py|jina/proto/pb2/docarray_pb2.py|jina/proto/pb2/docarray_pb2_grpc.py)
    args:
      - --max-complexity=10
      - --max-line-length=127
      - --select=E9,F63,F7,F82

- repo: https://github.com/asottile/blacken-docs
  rev: 1.14.0
  hooks:
  - id: blacken-docs
    args:
      - -S

default_language_version:
    python: python3.10
